version: '3.7'

services:
  app:
    build: .
    container_name: app
    environment:
      - SERVER_ADDRESS="0.0.0.0:8080"
      - POSTGRES_CONN="postgres://postgres:postgres@172.18.1.2:5432/avito?sslmode=disable"
      - POSTGRES_JDBC_URL="jdbc:postgresql://your_host:your_port/your_db"
      - POSTGRES_USERNAME="postgres"
      - POSTGRES_PASSWORD="postgres"
      - POSTGRES_HOST="172.18.1.2"
      - POSTGRES_PORT="5432"
      - POSTGRES_DATABASE="avito"
    networks:
      my_net:
        ipv4_address: 172.18.1.3

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=avito
      - POSTGRES_SSL_MODE=disable
    networks:
      my_net:
        ipv4_address: 172.18.1.2
volumes:
  post_avito_data:

networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/24