version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=avito
      - POSTGRES_SSL_MODE=disable
    networks:
      my_net:
        ipv4_address: 172.18.1.2
volumes:
  post_avito_data:

networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/24